/**
 * Shared primitives.
 *
 * Kept in one module because the set is small and every page uses most of it.
 * The pieces that matter for correctness are `EmptyState`, `ErrorState` and
 * `Loading`: every page that fetches renders one of the four states explicitly,
 * so no screen can ever show `undefined` or a chart with no data in it.
 */
import clsx from 'clsx'
import {
  AlertTriangle,
  Check,
  ChevronLeft,
  ChevronRight,
  Copy,
  Inbox,
  Loader2,
  X,
} from 'lucide-react'
import {
  type ReactNode,
  createContext,
  useCallback,
  useContext,
  useEffect,
  useId,
  useState,
} from 'react'

import { percent } from '@/utils/format'
import { riskBand, severityMeta, statusMeta } from '@/utils/severity'

// ---------------------------------------------------------------- containers
export function Panel({
  children,
  className,
  title,
  subtitle,
  actions,
  dense,
}: {
  children: ReactNode
  className?: string
  title?: ReactNode
  subtitle?: ReactNode
  actions?: ReactNode
  dense?: boolean
}) {
  return (
    <section className={clsx('panel animate-fade-in', className)}>
      {(title || actions) && (
        <header className="panel-header">
          <div className="min-w-0">
            {title && <h2 className="text-sm font-semibold text-ink truncate">{title}</h2>}
            {subtitle && <p className="text-xs text-ink-muted mt-0.5">{subtitle}</p>}
          </div>
          {actions && <div className="flex items-center gap-2 shrink-0">{actions}</div>}
        </header>
      )}
      <div className={dense ? '' : 'p-4'}>{children}</div>
    </section>
  )
}

export function SectionHeading({ children, hint }: { children: ReactNode; hint?: string }) {
  return (
    <div className="flex items-baseline gap-2 mb-2">
      <h3 className="label">{children}</h3>
      {hint && <span className="text-2xs text-ink-faint">{hint}</span>}
    </div>
  )
}

// -------------------------------------------------------------------- badges
export function Badge({
  children,
  className,
  title,
}: {
  children: ReactNode
  className?: string
  title?: string
}) {
  return (
    <span className={clsx('chip border-line bg-raised text-ink-muted', className)} title={title}>
      {children}
    </span>
  )
}

export function SeverityBadge({ severity, showLabel = true }: { severity: string; showLabel?: boolean }) {
  const meta = severityMeta(severity)
  return (
    <span
      className={clsx('chip', meta.bg, meta.border, meta.text)}
      title={`Severity: ${meta.label}`}
    >
      <span aria-hidden="true">{meta.glyph}</span>
      {showLabel && <span>{meta.label}</span>}
    </span>
  )
}

export function StatusBadge({ status }: { status: string }) {
  const meta = statusMeta(status)
  return <span className={clsx('chip', meta.bg, meta.border, meta.text)}>{meta.label}</span>
}

export function RiskScore({ score, showBar = true }: { score: number; showBar?: boolean }) {
  const meta = severityMeta(riskBand(score))
  return (
    <div className="flex items-center gap-2 min-w-[80px]">
      <span className={clsx('tabular-nums font-semibold text-sm', meta.text)}>
        {score.toFixed(0)}
      </span>
      {showBar && (
        <div
          className="h-1.5 flex-1 bg-raised rounded-full overflow-hidden min-w-[36px]"
          role="img"
          aria-label={`Risk score ${score.toFixed(0)} of 100, ${meta.label}`}
        >
          <div
            className="h-full rounded-full transition-all"
            style={{ width: `${Math.min(100, Math.max(2, score))}%`, backgroundColor: meta.hex }}
          />
        </div>
      )}
    </div>
  )
}

export function ConfidenceBadge({ value }: { value: number }) {
  const tone =
    value >= 0.8 ? 'text-healthy' : value >= 0.6 ? 'text-medium' : 'text-ink-muted'
  return (
    <span className={clsx('tabular-nums text-xs font-medium', tone)} title="Detection confidence">
      {percent(value)}
    </span>
  )
}

export function DemoTag() {
  return (
    <span
      className="chip border-line-strong bg-raised text-ink-faint"
      title="Generated by the SENTINEL-X attack simulator. Not a real security incident."
    >
      SIMULATED
    </span>
  )
}

// --------------------------------------------------------------- page states
export function Loading({ label = 'Loading', rows = 3 }: { label?: string; rows?: number }) {
  return (
    <div className="p-4 space-y-2" role="status" aria-live="polite" aria-busy="true">
      <span className="sr-only">{label}</span>
      {Array.from({ length: rows }).map((_, index) => (
        <div
          key={index}
          className="relative h-8 rounded bg-raised/60 overflow-hidden"
          style={{ opacity: 1 - index * 0.15 }}
        >
          <div className="absolute inset-0 -translate-x-full animate-shimmer bg-gradient-to-r from-transparent via-line/40 to-transparent" />
        </div>
      ))}
    </div>
  )
}

export function Spinner({ className }: { className?: string }) {
  return <Loader2 className={clsx('h-4 w-4 animate-spin', className)} aria-hidden="true" />
}

export function EmptyState({
  title,
  description,
  action,
  icon,
}: {
  title: string
  description?: string
  action?: ReactNode
  icon?: ReactNode
}) {
  return (
    <div className="flex flex-col items-center justify-center gap-2 py-12 px-6 text-center">
      <div className="text-ink-faint" aria-hidden="true">
        {icon ?? <Inbox className="h-7 w-7" />}
      </div>
      <p className="text-sm font-medium text-ink">{title}</p>
      {description && <p className="text-xs text-ink-muted max-w-md">{description}</p>}
      {action && <div className="mt-2">{action}</div>}
    </div>
  )
}

export function ErrorState({
  error,
  onRetry,
  context,
}: {
  error: unknown
  onRetry?: () => void
  context?: string
}) {
  const message =
    error instanceof Error ? error.message : 'An unexpected error occurred.'
  const code = (error as { code?: string })?.code
  return (
    <div
      className="flex flex-col items-center justify-center gap-2 py-10 px-6 text-center"
      role="alert"
    >
      <AlertTriangle className="h-6 w-6 text-high" aria-hidden="true" />
      <p className="text-sm font-medium text-ink">{context ?? 'Could not load this view'}</p>
      <p className="text-xs text-ink-muted max-w-md">{message}</p>
      {code && <p className="mono text-ink-faint">{code}</p>}
      {onRetry && (
        <button type="button" className="btn-secondary mt-2" onClick={onRetry}>
          Try again
        </button>
      )}
    </div>
  )
}

/** Renders exactly one of loading / error / empty / content. */
export function QueryBoundary<T>({
  query,
  children,
  empty,
  context,
  loadingRows,
}: {
  query: { isLoading: boolean; isError: boolean; error: unknown; data: T | undefined; refetch: () => void }
  children: (data: T) => ReactNode
  empty?: { title: string; description?: string; action?: ReactNode } | ((data: T) => boolean)
  context?: string
  loadingRows?: number
}) {
  if (query.isLoading) return <Loading rows={loadingRows} />
  if (query.isError) return <ErrorState error={query.error} onRetry={query.refetch} context={context} />
  if (query.data === undefined) {
    return <EmptyState title="No data available" />
  }
  if (empty && typeof empty === 'object') {
    const value = query.data as unknown
    const isEmpty =
      Array.isArray(value)
        ? value.length === 0
        : typeof value === 'object' &&
          value !== null &&
          'items' in value &&
          Array.isArray((value as { items: unknown[] }).items) &&
          (value as { items: unknown[] }).items.length === 0
    if (isEmpty) return <EmptyState {...empty} />
  }
  return <>{children(query.data)}</>
}

// --------------------------------------------------------------------- tabs
interface TabsContextValue {
  active: string
  setActive: (value: string) => void
  baseId: string
}
const TabsContext = createContext<TabsContextValue | null>(null)

export function Tabs({
  tabs,
  active,
  onChange,
  children,
  className,
}: {
  tabs: { id: string; label: string; badge?: ReactNode }[]
  active: string
  onChange: (id: string) => void
  children: ReactNode
  className?: string
}) {
  const baseId = useId()

  const onKeyDown = (event: React.KeyboardEvent) => {
    const index = tabs.findIndex((t) => t.id === active)
    if (event.key === 'ArrowRight') {
      event.preventDefault()
      onChange(tabs[(index + 1) % tabs.length].id)
    } else if (event.key === 'ArrowLeft') {
      event.preventDefault()
      onChange(tabs[(index - 1 + tabs.length) % tabs.length].id)
    }
  }

  return (
    <TabsContext.Provider value={{ active, setActive: onChange, baseId }}>
      <div className={className}>
        <div
          role="tablist"
          aria-label="Investigation sections"
          onKeyDown={onKeyDown}
          className="flex items-center gap-1 overflow-x-auto border-b border-line px-1"
        >
          {tabs.map((tab) => {
            const selected = tab.id === active
            return (
              <button
                key={tab.id}
                id={`${baseId}-tab-${tab.id}`}
                role="tab"
                type="button"
                aria-selected={selected}
                aria-controls={`${baseId}-panel-${tab.id}`}
                tabIndex={selected ? 0 : -1}
                onClick={() => onChange(tab.id)}
                className={clsx(
                  'px-3 py-2 text-sm whitespace-nowrap border-b-2 -mb-px transition-colors flex items-center gap-1.5',
                  selected
                    ? 'border-accent text-ink font-medium'
                    : 'border-transparent text-ink-muted hover:text-ink',
                )}
              >
                {tab.label}
                {tab.badge !== undefined && tab.badge !== null && (
                  <span className="text-2xs text-ink-faint tabular-nums">{tab.badge}</span>
                )}
              </button>
            )
          })}
        </div>
        {children}
      </div>
    </TabsContext.Provider>
  )
}

export function TabPanel({ id, children }: { id: string; children: ReactNode }) {
  const context = useContext(TabsContext)
  if (!context || context.active !== id) return null
  return (
    <div
      role="tabpanel"
      id={`${context.baseId}-panel-${id}`}
      aria-labelledby={`${context.baseId}-tab-${id}`}
      tabIndex={0}
      className="animate-slide-up focus-visible:outline-none"
    >
      {children}
    </div>
  )
}

// -------------------------------------------------------------------- modal
export function Modal({
  open,
  onClose,
  title,
  children,
  footer,
  wide,
}: {
  open: boolean
  onClose: () => void
  title: string
  children: ReactNode
  footer?: ReactNode
  wide?: boolean
}) {
  useEffect(() => {
    if (!open) return
    const handler = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose()
    }
    document.addEventListener('keydown', handler)
    return () => document.removeEventListener('keydown', handler)
  }, [open, onClose])

  if (!open) return null
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 animate-fade-in"
      role="dialog"
      aria-modal="true"
      aria-label={title}
      onClick={(event) => {
        if (event.target === event.currentTarget) onClose()
      }}
    >
      <div
        className={clsx(
          'bg-surface border border-line rounded-lg shadow-pop w-full flex flex-col max-h-[85vh]',
          wide ? 'max-w-4xl' : 'max-w-lg',
        )}
      >
        <div className="panel-header">
          <h2 className="text-sm font-semibold">{title}</h2>
          <button type="button" className="btn-ghost p-1" onClick={onClose} aria-label="Close">
            <X className="h-4 w-4" />
          </button>
        </div>
        <div className="p-4 overflow-y-auto flex-1">{children}</div>
        {footer && <div className="px-4 py-3 border-t border-line flex justify-end gap-2">{footer}</div>}
      </div>
    </div>
  )
}

// --------------------------------------------------------------- pagination
export function Pagination({
  total,
  limit,
  offset,
  onChange,
}: {
  total: number
  limit: number
  offset: number
  onChange: (offset: number) => void
}) {
  const page = Math.floor(offset / limit) + 1
  const pages = Math.max(1, Math.ceil(total / limit))
  if (total <= limit) {
    return (
      <p className="text-2xs text-ink-faint px-3 py-2">
        {total} {total === 1 ? 'result' : 'results'}
      </p>
    )
  }
  return (
    <nav className="flex items-center justify-between px-3 py-2 gap-3" aria-label="Pagination">
      <p className="text-2xs text-ink-faint tabular-nums">
        {offset + 1}–{Math.min(offset + limit, total)} of {total}
      </p>
      <div className="flex items-center gap-1">
        <button
          type="button"
          className="btn-ghost px-2 py-1"
          disabled={offset === 0}
          onClick={() => onChange(Math.max(0, offset - limit))}
          aria-label="Previous page"
        >
          <ChevronLeft className="h-4 w-4" />
        </button>
        <span className="text-2xs text-ink-muted tabular-nums px-1">
          {page} / {pages}
        </span>
        <button
          type="button"
          className="btn-ghost px-2 py-1"
          disabled={offset + limit >= total}
          onClick={() => onChange(offset + limit)}
          aria-label="Next page"
        >
          <ChevronRight className="h-4 w-4" />
        </button>
      </div>
    </nav>
  )
}

// ------------------------------------------------------------------- misc
export function CopyButton({ value, label = 'Copy' }: { value: string; label?: string }) {
  const [copied, setCopied] = useState(false)
  const copy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 1400)
    } catch {
      /* clipboard unavailable (insecure context) — fail quietly */
    }
  }, [value])

  return (
    <button type="button" className="btn-ghost px-1.5 py-1" onClick={copy} aria-label={label}>
      {copied ? <Check className="h-3.5 w-3.5 text-healthy" /> : <Copy className="h-3.5 w-3.5" />}
    </button>
  )
}

export function KeyValue({
  items,
  columns = 2,
}: {
  items: { label: string; value: ReactNode; title?: string }[]
  columns?: 1 | 2 | 3
}) {
  return (
    <dl
      className={clsx(
        'grid gap-x-6 gap-y-3',
        columns === 1 && 'grid-cols-1',
        columns === 2 && 'grid-cols-1 sm:grid-cols-2',
        columns === 3 && 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3',
      )}
    >
      {items.map((item) => (
        <div key={item.label} className="min-w-0">
          <dt className="label mb-0.5">{item.label}</dt>
          <dd className="text-sm text-ink break-words" title={item.title}>
            {item.value ?? '—'}
          </dd>
        </div>
      ))}
    </dl>
  )
}

export function Code({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <code className={clsx('mono bg-base border border-line rounded px-1.5 py-0.5 text-ink-muted', className)}>
      {children}
    </code>
  )
}

export function CodeBlock({ content, maxHeight = 320 }: { content: string; maxHeight?: number }) {
  return (
    <pre
      className="mono bg-base border border-line rounded-md p-3 overflow-auto text-ink-muted whitespace-pre-wrap break-words"
      style={{ maxHeight }}
    >
      {content}
    </pre>
  )
}

export function Callout({
  tone = 'info',
  title,
  children,
}: {
  tone?: 'info' | 'warning' | 'critical' | 'healthy'
  title?: string
  children: ReactNode
}) {
  const tones = {
    info: 'border-low/40 bg-low/5 text-ink-muted',
    warning: 'border-medium/40 bg-medium/5 text-ink-muted',
    critical: 'border-critical/40 bg-critical/5 text-ink-muted',
    healthy: 'border-healthy/40 bg-healthy/5 text-ink-muted',
  }
  return (
    <div className={clsx('border rounded-md p-3 text-xs leading-relaxed', tones[tone])}>
      {title && <p className="font-semibold text-ink mb-1">{title}</p>}
      {children}
    </div>
  )
}

export function ProgressBar({
  value,
  max = 100,
  color = '#22d3ee',
  label,
}: {
  value: number
  max?: number
  color?: string
  label?: string
}) {
  const pct = max > 0 ? Math.min(100, Math.max(0, (value / max) * 100)) : 0
  return (
    <div
      className="h-1.5 w-full bg-raised rounded-full overflow-hidden"
      role="progressbar"
      aria-valuenow={value}
      aria-valuemin={0}
      aria-valuemax={max}
      aria-label={label}
    >
      <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, backgroundColor: color }} />
    </div>
  )
}
