"""Cloud security."""

from __future__ import annotations

from typing import Annotated, Any

from fastapi import APIRouter, Query

from app.api.deps import DbSession, RequireViewer
from app.services.cloud import (
    account_summary,
    cloud_overview,
    iam_changes,
    identity_activity_graph,
    risky_identities,
)

router = APIRouter(prefix="/cloud", tags=["cloud"])

CLOUD_NOTICE = (
    "SENTINEL-X requires no cloud credentials and makes no calls to any cloud provider. "
    "It consumes control-plane audit records, which is exactly how a real detection "
    "pipeline sees cloud activity. In this deployment those records are generated by the "
    "attack simulator and the evaluation dataset."
)


@router.get("/overview", summary="Cloud security posture")
def overview(
    db: DbSession,
    _: RequireViewer,
    window_hours: Annotated[int, Query(ge=1, le=24 * 90)] = 168,
) -> dict[str, Any]:
    return {"notice": CLOUD_NOTICE, **cloud_overview(db, window_hours=window_hours)}


@router.get("/accounts", summary="Cloud accounts")
def accounts(
    db: DbSession,
    _: RequireViewer,
    window_hours: Annotated[int, Query(ge=1, le=24 * 90)] = 168,
) -> list[dict[str, Any]]:
    return account_summary(db, window_hours=window_hours)


@router.get("/identities", summary="Identities ranked by explainable risk")
def identities(
    db: DbSession,
    _: RequireViewer,
    window_hours: Annotated[int, Query(ge=1, le=24 * 90)] = 168,
    limit: Annotated[int, Query(ge=1, le=100)] = 25,
) -> dict[str, Any]:
    return {
        "notice": CLOUD_NOTICE,
        "risk_model": (
            "Weighted factors: privilege operations (0.30), denied attempts (0.20), "
            "defense evasion (0.20), MFA-less calls (0.15), external source addresses "
            "(0.15). Each identity carries the full factor breakdown."
        ),
        "identities": risky_identities(db, window_hours=window_hours, limit=limit),
    }


@router.get("/iam-changes", summary="Permission-affecting operations")
def changes(
    db: DbSession,
    _: RequireViewer,
    window_hours: Annotated[int, Query(ge=1, le=24 * 90)] = 168,
    limit: Annotated[int, Query(ge=1, le=500)] = 100,
) -> list[dict[str, Any]]:
    return iam_changes(db, window_hours=window_hours, limit=limit)


@router.get("/identities/{identity}/graph", summary="identity -> API call -> resource")
def identity_graph(
    identity: str,
    db: DbSession,
    _: RequireViewer,
    window_hours: Annotated[int, Query(ge=1, le=24 * 90)] = 168,
) -> dict[str, Any]:
    return identity_activity_graph(db, identity, window_hours=window_hours)
