"""initial schema

Revision ID: 43db391bedca
Revises: 
Create Date: 2026-09-15 18:09:49.299188
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# app/core/timeutils.UTCDateTime is a TypeDecorator that forces UTC in
# and out; autogenerate renders it by its qualified name.
import app.core.timeutils  # noqa: F401

revision: str = '43db391bedca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=48), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_action', 'audit_logs', ['actor', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor'), 'audit_logs', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_table('behavior_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_ref', sa.String(length=128), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_observed', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_ref', 'feature', name='uq_baseline_entity_feature')
    )
    op.create_index(op.f('ix_behavior_baselines_entity_ref'), 'behavior_baselines', ['entity_ref'], unique=False)
    op.create_index(op.f('ix_behavior_baselines_entity_type'), 'behavior_baselines', ['entity_type'], unique=False)
    op.create_index(op.f('ix_behavior_baselines_feature'), 'behavior_baselines', ['feature'], unique=False)
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('mitre_techniques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tactics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=24), nullable=False),
    sa.Column('references', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('false_positives', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tests', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_category'), 'detection_rules', ['category'], unique=False)
    op.create_index(op.f('ix_detection_rules_enabled'), 'detection_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_detection_rules_rule_id'), 'detection_rules', ['rule_id'], unique=True)
    op.create_index(op.f('ix_detection_rules_rule_type'), 'detection_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_detection_rules_severity'), 'detection_rules', ['severity'], unique=False)
    op.create_index('ix_rules_enabled_type', 'detection_rules', ['enabled', 'rule_type'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eval_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('dataset_name', sa.String(length=128), nullable=False),
    sa.Column('dataset_seed', sa.Integer(), nullable=False),
    sa.Column('dataset_size', sa.Integer(), nullable=False),
    sa.Column('benign_count', sa.Integer(), nullable=False),
    sa.Column('malicious_count', sa.Integer(), nullable=False),
    sa.Column('ambiguous_count', sa.Integer(), nullable=False),
    sa.Column('true_positives', sa.Integer(), nullable=False),
    sa.Column('false_positives', sa.Integer(), nullable=False),
    sa.Column('true_negatives', sa.Integer(), nullable=False),
    sa.Column('false_negatives', sa.Integer(), nullable=False),
    sa.Column('precision', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=False),
    sa.Column('median_latency_ms', sa.Float(), nullable=False),
    sa.Column('p95_latency_ms', sa.Float(), nullable=False),
    sa.Column('per_scenario', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('per_rule', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_started', 'evaluation_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_evaluation_runs_eval_id'), 'evaluation_runs', ['eval_id'], unique=True)
    op.create_index(op.f('ix_evaluation_runs_started_at'), 'evaluation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_status'), 'evaluation_runs', ['status'], unique=False)
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_family', sa.String(length=32), nullable=False),
    sa.Column('os_version', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_isolated', sa.Boolean(), nullable=False),
    sa.Column('isolated_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('first_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_host_id'), 'hosts', ['host_id'], unique=True)
    op.create_index(op.f('ix_hosts_ip_address'), 'hosts', ['ip_address'], unique=False)
    op.create_index('ix_hosts_risk', 'hosts', [sa.literal_column('risk_score DESC')], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_id', sa.String(length=64), nullable=False),
    sa.Column('indicator', sa.String(length=512), nullable=False),
    sa.Column('ioc_type', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'ioc_type', name='uq_ioc_value_type')
    )
    op.create_index(op.f('ix_iocs_indicator'), 'iocs', ['indicator'], unique=False)
    op.create_index(op.f('ix_iocs_ioc_id'), 'iocs', ['ioc_id'], unique=True)
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_is_active'), 'iocs', ['is_active'], unique=False)
    op.create_index('ix_iocs_type_active', 'iocs', ['ioc_type', 'is_active'], unique=False)
    op.create_table('mitre_tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tactic_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('shortname', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mitre_tactics_tactic_id'), 'mitre_tactics', ['tactic_id'], unique=True)
    op.create_table('mitre_techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tactic_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_subtechnique', sa.Boolean(), nullable=False),
    sa.Column('parent_technique_id', sa.String(length=24), nullable=True),
    sa.Column('platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('data_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detection_guidance', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mitre_parent', 'mitre_techniques', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_parent_technique_id'), 'mitre_techniques', ['parent_technique_id'], unique=False)
    op.create_index(op.f('ix_mitre_techniques_technique_id'), 'mitre_techniques', ['technique_id'], unique=True)
    op.create_table('saved_hunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('query', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_hunts_name'), 'saved_hunts', ['name'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=False),
    sa.Column('scenario_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('incident_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('alert_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_techniques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detected_techniques', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stage_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sim_scenario_started', 'simulation_runs', ['scenario', sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_simulation_runs_run_id'), 'simulation_runs', ['run_id'], unique=True)
    op.create_index(op.f('ix_simulation_runs_scenario'), 'simulation_runs', ['scenario'], unique=False)
    op.create_index(op.f('ix_simulation_runs_started_at'), 'simulation_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_simulation_runs_status'), 'simulation_runs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=128), nullable=True),
    sa.Column('is_privileged', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_risk', 'users', [sa.literal_column('risk_score DESC')], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('host_ref', sa.String(length=128), nullable=True),
    sa.Column('host_pk', sa.Integer(), nullable=True),
    sa.Column('user_ref', sa.String(length=128), nullable=True),
    sa.Column('user_pk', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('bytes_out', sa.Integer(), nullable=True),
    sa.Column('process_name', sa.String(length=255), nullable=True),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('parent_process', sa.String(length=255), nullable=True),
    sa.Column('command_line', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('cloud_provider', sa.String(length=32), nullable=True),
    sa.Column('cloud_account', sa.String(length=128), nullable=True),
    sa.Column('cloud_service', sa.String(length=64), nullable=True),
    sa.Column('cloud_resource', sa.Text(), nullable=True),
    sa.Column('cloud_region', sa.String(length=48), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('raw_event', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('simulation_run_pk', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=16), nullable=True),
    sa.Column('label_scenario', sa.String(length=64), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['host_pk'], ['hosts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_pk'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_pk'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_action'), 'events', ['action'], unique=False)
    op.create_index(op.f('ix_events_cloud_account'), 'events', ['cloud_account'], unique=False)
    op.create_index(op.f('ix_events_destination_ip'), 'events', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_file_hash'), 'events', ['file_hash'], unique=False)
    op.create_index(op.f('ix_events_host_ref'), 'events', ['host_ref'], unique=False)
    op.create_index('ix_events_host_ts', 'events', ['host_ref', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_ingested_at'), 'events', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_events_is_demo'), 'events', ['is_demo'], unique=False)
    op.create_index(op.f('ix_events_label'), 'events', ['label'], unique=False)
    op.create_index('ix_events_label_pair', 'events', ['label', 'label_scenario'], unique=False)
    op.create_index(op.f('ix_events_label_scenario'), 'events', ['label_scenario'], unique=False)
    op.create_index(op.f('ix_events_process_name'), 'events', ['process_name'], unique=False)
    op.create_index(op.f('ix_events_simulation_run_pk'), 'events', ['simulation_run_pk'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_source_ip'), 'events', ['source_ip'], unique=False)
    op.create_index('ix_events_srcip_ts', 'events', ['source_ip', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index('ix_events_type_ts', 'events', ['event_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_events_user_ref'), 'events', ['user_ref'], unique=False)
    op.create_index('ix_events_user_ts', 'events', ['user_ref', 'timestamp'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('first_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_reason', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attack_chain', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('affected_hosts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('affected_users', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('targeted_users', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_ips', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('destination_ips', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('technique_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ioc_matches', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('entity_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('closed_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=128), nullable=True),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('mttr_seconds', sa.Integer(), nullable=True),
    sa.Column('simulation_run_pk', sa.Integer(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_run_pk'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_first_seen'), 'incidents', ['first_seen'], unique=False)
    op.create_index(op.f('ix_incidents_incident_id'), 'incidents', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incidents_is_demo'), 'incidents', ['is_demo'], unique=False)
    op.create_index(op.f('ix_incidents_last_seen'), 'incidents', ['last_seen'], unique=False)
    op.create_index('ix_incidents_lastseen', 'incidents', [sa.literal_column('last_seen DESC')], unique=False)
    op.create_index(op.f('ix_incidents_risk_score'), 'incidents', ['risk_score'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_simulation_run_pk'), 'incidents', ['simulation_run_pk'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_sev', 'incidents', ['status', 'severity'], unique=False)
    op.create_table('ai_investigations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=True),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('task', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('validation_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('offered_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cited_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('injection_flagged', sa.Boolean(), nullable=False),
    sa.Column('injection_signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_investigations_created_at'), 'ai_investigations', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_investigations_incident_pk'), 'ai_investigations', ['incident_pk'], unique=False)
    op.create_index(op.f('ix_ai_investigations_validation_status'), 'ai_investigations', ['validation_status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('detected_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('first_event_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_event_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('detection_latency_ms', sa.Integer(), nullable=False),
    sa.Column('processing_latency_ms', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('host_ref', sa.String(length=128), nullable=True),
    sa.Column('user_ref', sa.String(length=128), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('technique_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tactics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('entity_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=True),
    sa.Column('simulation_run_pk', sa.Integer(), nullable=True),
    sa.Column('triaged_by', sa.String(length=128), nullable=True),
    sa.Column('triaged_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=True),
    sa.Column('false_positive_reason', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_run_pk'], ['simulation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index('ix_alerts_detected', 'alerts', [sa.literal_column('detected_at DESC')], unique=False)
    op.create_index(op.f('ix_alerts_detected_at'), 'alerts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_alerts_host_ref'), 'alerts', ['host_ref'], unique=False)
    op.create_index(op.f('ix_alerts_incident_pk'), 'alerts', ['incident_pk'], unique=False)
    op.create_index(op.f('ix_alerts_is_demo'), 'alerts', ['is_demo'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_simulation_run_pk'), 'alerts', ['simulation_run_pk'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_sev', 'alerts', ['status', 'severity'], unique=False)
    op.create_index(op.f('ix_alerts_user_ref'), 'alerts', ['user_ref'], unique=False)
    op.create_table('analyst_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyst_notes_incident_pk'), 'analyst_notes', ['incident_pk'], unique=False)
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=False),
    sa.Column('event_pk', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['event_pk'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_pk', 'event_pk', name='uq_incident_event')
    )
    op.create_index(op.f('ix_incident_events_event_pk'), 'incident_events', ['event_pk'], unique=False)
    op.create_index(op.f('ix_incident_events_incident_pk'), 'incident_events', ['incident_pk'], unique=False)
    op.create_table('incident_techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=24), nullable=False),
    sa.Column('tactic_id', sa.String(length=24), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_observed', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_observed', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('detected_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('evidence_event_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_rule_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_pk', 'technique_id', name='uq_incident_technique')
    )
    op.create_index(op.f('ix_incident_techniques_incident_pk'), 'incident_techniques', ['incident_pk'], unique=False)
    op.create_index(op.f('ix_incident_techniques_tactic_id'), 'incident_techniques', ['tactic_id'], unique=False)
    op.create_index(op.f('ix_incident_techniques_technique_id'), 'incident_techniques', ['technique_id'], unique=False)
    op.create_table('ioc_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_pk', sa.Integer(), nullable=False),
    sa.Column('event_pk', sa.Integer(), nullable=False),
    sa.Column('matched_field', sa.String(length=64), nullable=False),
    sa.Column('matched_value', sa.String(length=512), nullable=False),
    sa.Column('matched_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_pk'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ioc_pk'], ['iocs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ioc_pk', 'event_pk', 'matched_field', name='uq_ioc_match')
    )
    op.create_index(op.f('ix_ioc_matches_event_pk'), 'ioc_matches', ['event_pk'], unique=False)
    op.create_index(op.f('ix_ioc_matches_ioc_pk'), 'ioc_matches', ['ioc_pk'], unique=False)
    op.create_index(op.f('ix_ioc_matches_matched_at'), 'ioc_matches', ['matched_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_assisted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_incident_pk'), 'reports', ['incident_pk'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('incident_pk', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=48), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('playbook_id', sa.String(length=64), nullable=True),
    sa.Column('playbook_step', sa.Integer(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.core.timeutils.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_pk'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_action_id'), 'response_actions', ['action_id'], unique=True)
    op.create_index(op.f('ix_response_actions_action_type'), 'response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_actions_created_at'), 'response_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_response_actions_incident_pk'), 'response_actions', ['incident_pk'], unique=False)
    op.create_index(op.f('ix_response_actions_target'), 'response_actions', ['target'], unique=False)
    op.create_index('ix_response_incident_type', 'response_actions', ['incident_pk', 'action_type'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_pk', sa.Integer(), nullable=False),
    sa.Column('event_pk', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('step', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['alert_pk'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_pk'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_pk', 'event_pk', name='uq_alert_event')
    )
    op.create_index(op.f('ix_alert_events_alert_pk'), 'alert_events', ['alert_pk'], unique=False)
    op.create_index(op.f('ix_alert_events_event_pk'), 'alert_events', ['event_pk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_event_pk'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_alert_pk'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_response_incident_type', table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_target'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_incident_pk'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_created_at'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_action_type'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_action_id'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_incident_pk'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_ioc_matches_matched_at'), table_name='ioc_matches')
    op.drop_index(op.f('ix_ioc_matches_ioc_pk'), table_name='ioc_matches')
    op.drop_index(op.f('ix_ioc_matches_event_pk'), table_name='ioc_matches')
    op.drop_table('ioc_matches')
    op.drop_index(op.f('ix_incident_techniques_technique_id'), table_name='incident_techniques')
    op.drop_index(op.f('ix_incident_techniques_tactic_id'), table_name='incident_techniques')
    op.drop_index(op.f('ix_incident_techniques_incident_pk'), table_name='incident_techniques')
    op.drop_table('incident_techniques')
    op.drop_index(op.f('ix_incident_events_incident_pk'), table_name='incident_events')
    op.drop_index(op.f('ix_incident_events_event_pk'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_analyst_notes_incident_pk'), table_name='analyst_notes')
    op.drop_table('analyst_notes')
    op.drop_index(op.f('ix_alerts_user_ref'), table_name='alerts')
    op.drop_index('ix_alerts_status_sev', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_simulation_run_pk'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_demo'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_incident_pk'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_host_ref'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_detected_at'), table_name='alerts')
    op.drop_index('ix_alerts_detected', table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_ai_investigations_validation_status'), table_name='ai_investigations')
    op.drop_index(op.f('ix_ai_investigations_incident_pk'), table_name='ai_investigations')
    op.drop_index(op.f('ix_ai_investigations_created_at'), table_name='ai_investigations')
    op.drop_table('ai_investigations')
    op.drop_index('ix_incidents_status_sev', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_simulation_run_pk'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_risk_score'), table_name='incidents')
    op.drop_index('ix_incidents_lastseen', table_name='incidents')
    op.drop_index(op.f('ix_incidents_last_seen'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_demo'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_first_seen'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_events_user_ts', table_name='events')
    op.drop_index(op.f('ix_events_user_ref'), table_name='events')
    op.drop_index('ix_events_type_ts', table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index('ix_events_srcip_ts', table_name='events')
    op.drop_index(op.f('ix_events_source_ip'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_events_simulation_run_pk'), table_name='events')
    op.drop_index(op.f('ix_events_process_name'), table_name='events')
    op.drop_index(op.f('ix_events_label_scenario'), table_name='events')
    op.drop_index('ix_events_label_pair', table_name='events')
    op.drop_index(op.f('ix_events_label'), table_name='events')
    op.drop_index(op.f('ix_events_is_demo'), table_name='events')
    op.drop_index(op.f('ix_events_ingested_at'), table_name='events')
    op.drop_index('ix_events_host_ts', table_name='events')
    op.drop_index(op.f('ix_events_host_ref'), table_name='events')
    op.drop_index(op.f('ix_events_file_hash'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_destination_ip'), table_name='events')
    op.drop_index(op.f('ix_events_cloud_account'), table_name='events')
    op.drop_index(op.f('ix_events_action'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index('ix_users_risk', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_simulation_runs_status'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_started_at'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_scenario'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_run_id'), table_name='simulation_runs')
    op.drop_index('ix_sim_scenario_started', table_name='simulation_runs')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_saved_hunts_name'), table_name='saved_hunts')
    op.drop_table('saved_hunts')
    op.drop_index(op.f('ix_mitre_techniques_technique_id'), table_name='mitre_techniques')
    op.drop_index(op.f('ix_mitre_techniques_parent_technique_id'), table_name='mitre_techniques')
    op.drop_index('ix_mitre_parent', table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index(op.f('ix_mitre_tactics_tactic_id'), table_name='mitre_tactics')
    op.drop_table('mitre_tactics')
    op.drop_index('ix_iocs_type_active', table_name='iocs')
    op.drop_index(op.f('ix_iocs_is_active'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_id'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_indicator'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_index('ix_hosts_risk', table_name='hosts')
    op.drop_index(op.f('ix_hosts_ip_address'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_host_id'), table_name='hosts')
    op.drop_table('hosts')
    op.drop_index(op.f('ix_evaluation_runs_status'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_started_at'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_eval_id'), table_name='evaluation_runs')
    op.drop_index('ix_eval_started', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_rules_enabled_type', table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_severity'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_rule_type'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_rule_id'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_enabled'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_category'), table_name='detection_rules')
    op.drop_table('detection_rules')
    op.drop_index(op.f('ix_behavior_baselines_feature'), table_name='behavior_baselines')
    op.drop_index(op.f('ix_behavior_baselines_entity_type'), table_name='behavior_baselines')
    op.drop_index(op.f('ix_behavior_baselines_entity_ref'), table_name='behavior_baselines')
    op.drop_table('behavior_baselines')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('ix_audit_actor_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
